### ISSUE TITLE
AVG time multiplier

### ISSUE THREAD

**Issue by lockie** [unbit/django-uwsgi#11]
Hi and thanks for this nice package! I have a little question about it though.
On my test setup, when constanlty hitting F5, uwsgitop shows "27ms" in AVG column, whereas in django-uwsgi admin I see numbers like 27696, and judging by Firefox developer tools, it's more like 27 milliseconds actually.
Which leads me to the question, are you guys 100% sure you've got the time units right?

**Comment by MechanisM** [comment]
Yeah, need to be fixed.

**Comment by lockie** [comment]
Nice, thanks!

**Comment by MechanisM** [comment]
Работает? А то сделал с мобилы через браузер и не проверял еще. Вроде должно работать правильно теперь.

**Comment by lockie** [comment]
Завтра проверю, сейчас уже комп с рабочим проектом выключил.

**Comment by lockie** [comment]
Да, теперь всё ок :thumbsup:
Если что, подожди на pypi новую версию заливать, у меня будет ещё один багрепорт (только что заметил) и один пуллреквест.
