### ISSUE TITLE
Enhancement: reload command

### ISSUE THREAD

**Issue by eriktelepovsky** [unbit/django-uwsgi#40]
It would be great to have a management command to reload uwsgi.

**Comment by MechanisM** [comment]
Hello @eriktelepovsky! What's your use case for such functionality?
You can send pull request for it. Or you have to create your own management command, as example for reloading look [here](https://github.com/unbit/django-uwsgi/blob/master/django_uwsgi/views.py#L67).
it can be smth like:
```
from django_uwsgi import uwsgi

.... your management command....
    uwsgi.reload()
```

**Comment by eriktelepovsky** [comment]
Hi. When I deploy a new functionality in my project to VPS I need to reload uwsgi. So a simple management command would be helpful and it would be great if it was included in the django-uwsgi so I wouldn't have to make custom management command in every Django project I have.

**Comment by vstoykov** [comment]
@eriktelepovsky you can use `touch-reload` option to point to your `wsgi.py` file and simply `touch` your file when deploy.
You can read more at the documentation http://uwsgi-docs.readthedocs.io/en/latest/articles/TheArtOfGracefulReloading.html

**Comment by eriktelepovsky** [comment]
Hi.

Thank you guys for your hints. @vstoykov I would like to use native API if possible.

@MechanisM I ended with this code, but it doesn't work. Can you advice, please? Thank you:

```Python
from django.core.management.base import BaseCommand

from django_uwsgi import uwsgi


class Command(BaseCommand):
    help = "Reloads uWSGI application of the project."

    def handle(self, *args, **options):
        if uwsgi is not None and uwsgi.masterpid() > 0:
            uwsgi.reload()
            print('uWSGI reloaded!')
        else:
            print('The uWSGI master process is not active')
```

```
$ python manage.py reload_uwsgi
The uWSGI master process is not active
```

I confirm I can reload uWSGI in the admin successfully using this button:

![image](https://user-images.githubusercontent.com/2685808/41586918-401aaa9e-73ae-11e8-9e53-eafeb1cdba7c.png)

![image](https://user-images.githubusercontent.com/2685808/41586958-59b94ea6-73ae-11e8-8475-483e97db86c1.png)

**Comment by MechanisM** [comment]
Hello @eriktelepovsky! Management commands work outside of uWSGI. 
uWSGI can be imported and used in code only if you run code via uWSGI.

**Comment by eriktelepovsky** [comment]
Thank you @MechanisM 

So I presume, it is not possible to achieve my goal, is it?

**Comment by vstoykov** [comment]
@eriktelepovsky did you read what I and @MechanisM told you? Did you try to understand it? Did you read the documentations page that I linked? Did you try to understand it?

Sorry that I sound rude but I don't get your point. Why you need management command to restart your server at all?

Normally when you are executing your deployment process you execute shell script which is executing some commands. What is the problem instead of `python manage.py uwsgi_restart` or something like that to simply execute:

    touch -c path/to/your/wsgi.py

and to put in your uwsgi config file the following:

    wsgi-file = path/to/your/wsgi.py
    touch-reload = %(wsgi-file)

?

**Comment by eriktelepovsky** [comment]
Hi. Thank you for your reply. Yes, I understand it correctly. The reason is simple. I tried to make the reload process the most simple way. It was easier for me to call single management command then updating uwsgi config files in every project I have. But never mind, I will use ``uwsgi --reload wsgi.pid`` instead. Thank you again.

**Comment by san223deep** [comment]
> @eriktelepovsky did you read what I and @MechanisM told you? Did you try to understand it? Did you read the documentations page that I linked? Did you try to understand it?
> 
> Sorry that I sound rude but I don't get your point. Why you need management command to restart your server at all?
> 
> Normally when you are executing your deployment process you execute shell script which is executing some commands. What is the problem instead of `python manage.py uwsgi_restart` or something like that to simply execute:
> 
> ```
> touch -c path/to/your/wsgi.py
> ```
> 
> and to put in your uwsgi config file the following:
> 
> ```
> wsgi-file = path/to/your/wsgi.py
> touch-reload = %(wsgi-file)
> ```
> 
> ?

Hi, I read all conversation. I am using uwsgi and nginx to deploy django. I am using .ini to run uwsgi and uwsgi is installed in virtual environment.  Everything is fine. Now I used git pull to update code. (I am new and I have breaked things before so I am just confirming). So, if run `touch -c path/to/your/wsgi.py`, it will reload my website and if put ```
wsgi-file = path/to/your/wsgi.py
touch-reload = %(wsgi-file)
```
in my ini file, I dont have to do anything next time when I pull code?

**Comment by vstoykov** [comment]
@san223deep if you have in your uWSGI config
```
wsgi-file = path/to/your/wsgi.py
touch-reload = %(wsgi-file)
```
You need to always `touch -c path/to/your/wsgi.py` after `git pull` in order to reload your code after update.
